name: Conditons Lab

on: [push]

jobs:
  Print_Hello_World:
    if: github.repository=="octo-org/octo-repo-prod"
    runs-on: ubuntu-latest

    steps:
    - name: Hello_World
      run: |
        echo "Hello World" 
  
  Goodbye_Moon:
    runs-on: ubuntu-latest

    steps:
      - name: Goodbye_Moon_Print
        run: |
          echo "Goodbye Moon "
